/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface NeuQuantResult {
  indixes: Uint8Array
  colorMap: Uint8Array
}
export function neuquant(samplefac: number, colors: number, data: Uint8Array): NeuQuantResult
