/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface NeuQuantResult {
  indixes: Buffer
  colorMap: Buffer
}
export function neuquant(samplefac: number, colors: number, data: Buffer): NeuQuantResult
